### PR TITLE
Introducing a "magic" entry point.

### PR DESCRIPTION
**Pull request by WebReflection**
As discussed in [#90](https://github.com/WebReflection/hyperHTML/issues/90) it looks like developers might have easier life to use just one function that decides what to do based on given arguments.

  * ``hyper`<p>runtime</p>` `` to create one-off DOM content
  * ``hyper(node)`<p>bound content</p>` `` to use `node` as `hyperHTML.bind(context)`
  * ``hyper(obj, typeOrId)`<li>wire</li>` `` to create wires

This is going to be reflected on viper side too.

### CODE REVIEW

**Comment by grommett** [comment]
I'm torn on this. Apologies for chiming in late. I read #90 

I see the value in having one endpoint, however I also like the distinction between binding to an existing context and creating one with `wire`.  If you want to use and existing context use `bind`, if you want to create one use `wire`.

I'm just thinking how the docs might explain this new API  🤔  **and** `bind` & `wire`.

I'm assuming this works:

```js
const render = hyper(); // aka wire

function component(render, props) {
  return render`<p>${props.value}</p>`;
}

hyper(document.getElementById('app'))` // aka bind
  ${component(render, {value: 'hi'}}
`;
```

**Comment by WebReflection** [comment]
> I'm just thinking how the docs might explain this new API

this is not a new API, rather a shortcut. So, after explaining bind and wire regardless, the documentation should explain the hyper shortcut to cover 3 cases:

  * runtime, one off, DOM content creation with all the hyperHTML features (sanitized attributes and content, async, placeholders, etc)
  * wires when invoking
  * bind when invoking passing a DOM node to be used as context

> I'm assuming this works:

Yes, it does.


> I see the value in having one endpoint, however I also like the distinction between binding to an existing context and creating one with wire. It's clear - if you want to use and existing context use bind, if you want to create one use wire.

Apparently it's not as clear as I hoped.

This shortcut has less friction for newcomers, and it simulates lit-html entry point API (ditching the need for a scoped render, since render is bind in hyperHTML).

I'm not fully sold myself on this, but the current default export function is "useless" if used directly while this one ... it brings directly all the features and is more forgiving.

**Comment by joshgillies** [comment]
@WebReflection just to add my two cents in. I've been exploring exactly this API in user land recently, and overall find it much more enjoyable over the alternative.

The thing I like about this API is it gives you enough to get started, without adding a mental hurdle by introducing keywords like `bind` and `wire` up front. Which as far as I've seen developers don't generally fully appreciate until they've spent a few days working with `hyperHTML`.

So personally I'm 👍 on this.

**Comment by WebReflection** [comment]
So fare we have 2 happy ( @joshgillies @bigopon ) and 2 not fully convinced ( me and @grommett ) ... but nobody is against it :smiley: 

I wonder if @marcoscaceres has an opinion too

**Comment by grommett** [comment]
I'm sold. My apprehension was probably based more on the familiarity of how things work now, but it was pretty easy to come to an understanding of the new way. As @joshgillies points out, it shrinks the API and that is a win. 👍

**Comment by WebReflection** [comment]
OK @marcoscaceres , I've decided to move on with this since it's not a breaking change.

I'm still curious to know your opinion when/if you'll have time. Thanks.

**Comment by papas-source** [comment]
I am not fully convinced either, but I don't know why... 🤔

**Comment by WebReflection** [comment]
It worked well here:
https://github.com/webcomponents/custom-elements-everywhere/pull/10

**Comment by web3d0** [comment]
Seems like the hyperHTML version of handleEvent. Kind of slightly off, but works so well...?

**Pull request merged**
