### PR TITLE
fix #198: connected/disconnected events cannot dispatch to nested component

### LINKED ISSUE #198: connected/disconnected events cannot dispatch to nested components
This problem happened when the the parent of nested components has already bind connected/disconnected events.

```js
class ChildComponent extends hyper.Component
{
  onconnected(e) {
  }

  render() {
    return this.html`
      <div onconnected=${this}
         "I am a child"
      </div>
    `;
  }
}

class ParentComponent extends hyper.Component
{
  onconnected(e) {
  }

  render(){
    return this.html`
      <div onconnected=${this}
         ${new ChildComponent()}
      </div>
    `;
  }
}
```

In this circumstance, the child component won't receive the onconnected event.

The cause of this is [this piece of code](https://github.com/WebReflection/hyperHTML/blob/48012d189db0859ceef4d6f9c1ed3ba232828a70/esm/objects/Updates.js#L478). The parent component dispatches onconnect and skips the dispatch of child component.

### PR DESCRIPTION
**Pull request by liming**
This PR is trying to fix #198

### CODE REVIEW

**Comment by liming** [comment]
Added coverage files.

**Comment by WebReflection** [comment]
thanks for the PR but please not so easy ... I don't want events to dispatch twice if a parent with a connected callback has children with connected callbacks and there is no test around this PR.

Can we have a test case that ensure things work as expected and the parent doesn't trigger twice?
Thanks

**Comment by liming** [comment]
Hi @WebReflection ,

I don't understand why parent connected callback is triggered multiple times. I wrote the test case the parent connected callback is triggered multiple times (bubbling). But in real project it's only triggered once. Theoretically the CONNECTED & DISCONNECTED events would not bubble by default. Because the new Event has bubbles options default to false. 

I added test case to cover the events test. Could you help to have a look why it's not working? Thanks.

**Comment by WebReflection** [comment]
@liming it could be an issue in [basicHTML](https://github.com/WebReflection/basicHTML). Look, I might just merge this and figure out how to fix that but I'd like to be aligned on what we think should be the expected behaviour accordingly to [this change](https://github.com/WebReflection/hyperHTML/pull/199/commits/4f4e02650d7c69fe95af3b90327197f7c0b43571)

  1. the **parent** connected callback is dispatched **before** each child node
  2. **children** should dispatch **before** parent (as in bubbling order, even if no bubbling)

In top down order, the parent is connected and after its children but as bubbling/setup order one might expect children to fire before the parent ... or not?

I'm a bit puzzled, please help me with this and I'll merge your changes, fix the issue, and push the new version.

Thank You!

**Comment by WebReflection** [comment]
@liming I've counter-verified indeed there was a bug in basicHTML, now fixed (but it's not in here yet, will push changes ASAP)

**Comment by WebReflection** [comment]
@liming done.

If you could put in the `package.json` the version `"basichtml": "^0.13.2",` you won't have conflicts with master **and** the test should pass as expected.

Apologies for the inconvenient.

**Comment by liming** [comment]
Hi @WebReflection ,

I updated the package.json and test cases works! Thanks for the fix. It's good to merge and release a new patch :)

**Comment by WebReflection** [comment]
@liming please give me some quick thoughts on [this comment](https://github.com/WebReflection/hyperHTML/pull/199#issuecomment-367611610) and I'll eventually merge and release, thanks.

**Comment by liming** [comment]
Hi @WebReflection ,

The onconnect event is reflecting the sequence of DOM creation, in which the parents are created before children. Bubbling is the children letting their parent know something happened about themselves. If parents received an onconnect event bubbled from its child, this onconnect is actually say the child get birth instead of parent itself. The target of this event would be child but not parent.

We are talking about DOM creation order in regards to onconnect event. I think it make sense for parents receive the event before its children.

Does the explain make you less puzzled?

**Comment by WebReflection** [comment]
published as `v2.5.11`

**Pull request merged**
