### PR TITLE
hyper.Component

### PR DESCRIPTION
**Pull request by WebReflection**
This PR would like to add an extremely basic Component functionality.

Mosttly inspired by HyperHTMLElement, but actually hooked in core
to avoid needing at all costs Custom Elements.

The Component class provides most basic handleEvent mechanism
as seen in HyperHTMLElement class, plus a Preact-ish setState.

Instances can be passed directly as part of the template
or these can invoke comp.render() to return directly their wired content.

Every component will result into a wire, and every render() method
must return this.html`...` or this.svg`...`

This feature can be flagged as experimental until its viperHTML
counterpart is available.

The final goal is to recycle and reuse simple components via hyperHTML
and viperHTML stack.

### CODE REVIEW

**Comment by WebReflection** [comment]
I'd like @bigopon and @joshgillies opinion on this.

It's meant to work down to IE9 and it doesn't require Custom Elements.

It's about defining shareable components without transpiled builtin class issues and just good old known DOM.

Basic example:
```js
  class Button extends hyperHTML.Component {
    render() { return this.html`
      <button>hello</button>`;
    }
  }

  class Rect extends hyperHTML.Component {
    render() { return this.svg`
      <rect x=${this.state.x} y=${this.state.y} />`;
    }
  }

  class Paragraph extends hyperHTML.Component {
    onclick() { this.clicked = true; }
    render() { return this.html`
      <p attr=${this.state.attr} onclick=${this}>hello</p>`;
    }
  }

var div = document.createElement('div');
var render = hyperHTML.bind(div);
render`${[
  new Button,
  new Rect({x: 123, y: 456})
]}`;

var p = new Paragraph(() => ({attr: 'test'}));
render`${p}`;
p.render().click();
p.clicked; // true
```

Most of the functionalities are similar to HyperHTMLElement.

The features are kept to minimum on purpose.

**Any thought welcome.**

**Comment by WebReflection** [comment]
**viperHTML** counterpart is available.
https://github.com/WebReflection/viperHTML/pull/11

**Comment by joshgillies** [comment]
Really my only feedback is around something you're obviously already aware of:

> The final goal is to recycle and reuse simple components via hyperHTML and viperHTML stack.

This is something that we needed to overcome with `hypercomponent`. Which resulted in an API: [`component(Component, props, children)`](https://github.com/joshgillies/hypercomponent#componentcomponent-props-children).

Which internally simply maps the target child component to the instance of it's parent, ensuring child instance reuse on subsequent renders. It's a bit of a work-around, and we're exploring further alternatives as we speak.

Personally I'm really happy to see this feature land in `hyperHTML`, as it furthers the usefulness of `hyperHTML` right out of the box, without having to adopt all that comes with Custom Elements via `hyperHTML-Element` at this time.

Interestingly, assuming the intent is for `hyperHTML-Element` to become aware of `hyper.Component` this could further drive the adoption of Custom Elements. `hyperHTML-Element` <-> `hyper.Component` interop would be ✨ !

------

As a side comment on `this.html` - we had a similar pattern in `hypercomponent` though ditched it in favour of passing an "enhanced" wire via `html` as arguments to the render callback, which is nothing more than a facade over `wire(this, ...args)`.

Additionally, and further food for thought. I'm playing with the idea of having a generic `html` tagged template literal that simply maps to `const html = (statics, ...args) => [statics, ...args]`, allowing a user to return tagged template literal arguments from a render callback and have it magically resolve all the things under the hood, thus removing the requirement to pass `html` as an argument in the first place...

**Comment by WebReflection** [comment]
Thanks again @joshgillies , it's good to see developers expectations, so I can drop all my wrong/implicit assumptions, like setting a state, instead of props, to the constructor.

I am going to leave the constructor empty for now, it's easy to do what I've done already so it won't add anything, but it's also easy to fail expectations, since everyone uses both `state` and `props` because React does.

- - -

> internally simply maps the target child component to the instance of it's parent, ensuring child instance reuse on subsequent renders.

this is something similar to what _lit-html_ does too and to be honest I don't like it.

Current PR allows components as DOM nodes without needing parents to reuse themselves.

> It's a bit of a work-around, and we're exploring further alternatives as we speak.

if you find a better way it might land in core directly, not as API. Right now I am happy with performance and I cannot wait for _lit-html_ to create benchmarks so I can compare current wire logic VS their DOM/parentNode based approach. I think it's an easy win for `hyperHTML` here, and it also scales more, but never say never.

- - -

> Interestingly, assuming the intent is for hyperHTML-Element to become aware of hyper.Component 

Both share very similar (actually exact same) mechanism for `setState` with `get defaultState`, and the memory and performance friendly `handleEvent` goodness.

However, internally it's the core that understand components, so to some extend `HypweHTMLElement` classes are automatically aware of `hyper.Component` and can already use them.

- - -

> we had a similar pattern in hypercomponent though ditched it in favour of passing an "enhanced" wire via html as arguments to the render callback

I think having a method that receives from nowhere a parameter, or better nowhere defined by the user, is not the best way to go.

Moreover, this PR gives you the ability to pass properties on render directly.
```js
class Button extends hyper.Component {
  render(count) { return this.html`
    <button>${count}</button>`;
  }
}

class Counter extends hyper.Component {
  constructor() {
    super().state = {count: 0};
    this.button = new Button;
  }
  onclick(e) {
    this.setState({count: this.state.count + 1});
  }
  render() { return this.html`
    <div onclick=${this}>
      ${this.button.render(this.state.count)}
    </div>`;
  }
}

hyper.bind(document.body)`${new Counter}`;
```

This simple Component implementation should give you everything you need to extend, enrich, improve hyper components on top, including the ability to pass children or anything else.

Silly example coming:

```js
class HyperLazy extends hyper.Component {
  lazy(name, comp) {
    return this[name] = comp;
  }
}

class Counter extends HyperLazy {
  render() { return this.html`
    <div onclick=${this}>
      ${this.button || this.laz('button', new Button())}
    </div>`;
  }
}
```

- - -

Is there anything that you believe is an absolute must-have ?

**Comment by joshgillies** [comment]
> This simple Component implementation should give you everything you need to extend, enrich, improve hyper components on top, including the ability to pass children or anything else.

Completely agree, I think given the `hyper.Component` API as it currently stands gives developers enough to explore other patterns on-top. Really happy to see this land, and keen to integrate it into `hypercomponent` eventually.

> Is there anything that you believe is an absolute must-have ?

Really the only thing that could be considered a must-have given we're dealing with vanilla DOM are hooks for connectedCallback/disconnectedCallback... though the argument could be made that such a feature belongs in user-land.

**Comment by WebReflection** [comment]
> hooks for connectedCallback/disconnectedCallback

Without custom elements these hooks are kinda less useful. The moment you define the node is the moment it's there already. There is no upgrade mechanism.

> though the argument could be made that such a feature belongs in user-land.

being something not strictly necessary I'd say yes.

Having this mechanism in core would cost performance a lot. Using MutationObserver, also unpolyfillable for older targeted platforms, always put the browser in a state that is hard to come back from.

In WebKit, it affects performance on the whole document (same goes for Custom Elements though).

So I'd rather let userland decide when it's needed to have those mechanisms and when it's not.

Of course, if there is a nice pattern that won't bloat the core with MutationObserver polyfill and works in every target platform, I'd say why not. Diverging now though, it seems unnecessary.

I think I am going to ship this!

**Comment by joshgillies** [comment]
Excellent, nice work @WebReflection !

**Pull request merged**
