### PR TITLE
Remove all polyfills and updates dependencies

### PR DESCRIPTION
**Pull request by anthony-redFox**
BREAKING CHANGES:
Drop IE, Edge legacy and old browsers which are not support ES2015+ features

### CODE REVIEW

**Comment by anthony-redFox** [comment]
It was in 2.* npm-dollar size

62193
18082
7487
6851

New size is npm-dollar size

61556
16126
7114
6580

**Comment by anthony-redFox** [comment]
look like template-tag-arguments also could be dropped, I will do it tomorrow

**Comment by anthony-redFox** [comment]
I though that the project is maintains and regarding your message that you don't have a free time - https://github.com/WebReflection/hyperHTML/issues/413#issuecomment-1497659474
I am ok if you close PR.

**Comment by WebReflection** [comment]
> I though that the project is maintains

This project *is* in maintenance mode, meaning:

  * obvious bugs will be fixed
  * that's it

Changing or removing support for legacy browsers would require a major and a potential list of future issues to deal with due people not expecting the dropped support or having some slightly difference in the execution or maybe something was already fixed and using the standard without features detection broke things or maybe somebody is stuck in old TypeScript and removing the fix around templates break.

All of this or what ... 0.3K or less once minified? Hard pass, thanks!

**Pull request closed without merging**
